package models

var Licenses []string = []string{
	"Berkeley Database ",
	"Boost Software",
	"CeCILL version 2",
	"Clarified Artistic",
	"Cryptix General",
	"EU DataGrid Software",
	"Eiffel Forum , version 2",
	"Expat",
	"Intel Open Source (as published by OSI)",
	"Guile",
	"Netscape Javascript",
	"Perl",
	"Python 1.6a2 and earlier versions",
	"Python 2.0.1, 2.1.1, and newer versions",
	"Vim, version 6.1 or later",
	"ZLib",
	"iMatix Standard Function Library",
	"the run-time units of the GNU Ada compiler",
	"Modified BSD",
	"OpenLDAP , version 2.7",
	"Public Domain",
	"Standard ML of New Jersey Copyright",
	"Ruby",
	"W3C Software Notice",
	"X11",
	"Zope Public, version 2.0",
	"eCos, version 2.0",
	"MIT",
	"FreeBSD",
	"Berkeley Database",
	"Apache",
	"GNU",
	"Clear BSD",
	"Educational Community",
	"Freetype Project",
	"Historical Permission Notice",
	"Independent JPEG group",
	"informal",
	"ISC",
	"Mozilla",
}
