substitutions:
  _DIR_NAME: "delete_write_apis/"
  _ARTIFACT_REGISTRY_REPO_NAME: "container-repo"
  _WRITE_APIS_APP_CLOUD_RUN_NAME: "write-apis-app"
  _WRITE_APIS_APP_IMAGE_NAME: "write-apis-image"

steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_NAME}/${_WRITE_APIS_APP_IMAGE_NAME}',
           '.']
    dir: "${_DIR_NAME}"

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_NAME}/${_WRITE_APIS_APP_IMAGE_NAME}']
    dir: "${_DIR_NAME}"

  # Redeploy with new build (only updates the image)
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['beta', 'run', 'deploy', '${_WRITE_APIS_APP_CLOUD_RUN_NAME}',
            '--image', "us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_NAME}/${_WRITE_APIS_APP_IMAGE_NAME}:latest",
            '--region', 'us-central1']
            # '--allow-unauthenticated',
            # '--platform', 'managed']
